name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  BAKE_LOAD_ARGS: "--load"
  BAKE_CACHE_FROM: "*.cache-from=type=gha,scope=ci"
  BAKE_CACHE_TO: ""
  BAKE_OUTPUT: ""

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      BAKE_CACHE_TO: "*.cache-to=type=gha,mode=max,scope=ci"
      BAKE_OUTPUT: "*.output=type=cacheonly"
      BAKE_LOAD_ARGS: ""

    steps:
    - &checkout_step
      uses: actions/checkout@v4

    - &setup_buildx_step
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: image=moby/buildkit:buildx-stable-1

    - &bootstrap_step
      name: Bootstrap
      run: |
        ./script/bootstrap

    - &build_images_step
      name: Build Docker Images
      uses: docker/bake-action@v6
      with:
        source: "."
        files: "compose.yaml"
        push: false
        load: true
        set: ${{ format('dev.cache-from=type=gha,scope=ci{0}', env.BAKE_CACHE_TO != '' && format('\n{0}', env.BAKE_CACHE_TO) || '') }}
  
#   lint:
#     runs-on: ubuntu-latest
#     needs: build-image
#
#     steps:
#     - *checkout_step
#
#     - *setup_buildx_step
#
#     - *bootstrap_step
#
#     - *build_images_step
#
#     - name: Build images with docker compose
#       run: |
#         docker compose build dev
#
#     - name: Check formatting with ruff
#       run: |
#         docker compose run --rm --no-deps dev ruff format --check .
#
#     - name: Lint with ruff
#       run: |
#         docker compose run --rm --no-deps dev ruff check .
#
#     - name: Cleanup
#       if: always()
#       run: |
#         docker compose down -v
#
#   test:
#     runs-on: ubuntu-latest
#     needs: build-image
#
#     steps:
#     - *checkout_step
#
#     - *setup_buildx_step
#
#     - *bootstrap_step
#
#     - *build_images_step
#
#     - name: Build images with docker compose
#       run: |
#         docker compose build
#
#     - name: Run tests in dev container
#       run: |
#         docker compose run --rm dev pytest tests/ -v
#
#     - name: Show Cassandra logs on failure
#       if: failure()
#       run: |
#         docker compose logs cassandra
#
#     - name: Cleanup
#       if: always()
#       run: |
#         docker compose down -v
#
#   typecheck:
#     runs-on: ubuntu-latest
#     needs: build-image
#
#     steps:
#     - *checkout_step
#
#     - *setup_buildx_step
#
#     - *bootstrap_step
#
#     - *build_images_step
#
#     - name: Build images with docker compose
#       run: |
#         docker compose build dev
#
#     - name: Run tests in dev container
#       run: |
#         docker compose run --no-deps --rm dev mypy
#
#     - name: Show Cassandra logs on failure
#       if: failure()
#       run: |
#         docker compose logs cassandra
#
#     - name: Cleanup
#       if: always()
#       run: |
#         docker compose down -v
