name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  BAKE_LOAD_ARGS: "--load"
  BAKE_CACHE_TO_ARGS: ""

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      BAKE_CACHE_TO_ARGS: "--set dev.cache-to=type=gha,mode=max,scope=ci"
      BAKE_LOAD_ARGS: ""

    steps:
    - &checkout_step
      uses: actions/checkout@v4

    - &setup_buildx_step
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - &bootstrap_step
      name: Bootstrap
      run: |
        ./script/bootstrap

    - &build_images_step
      name: Warm cache
      env:
        DOCKER_BUILDKIT: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -eux
        CACHE_ARGS="${BAKE_CACHE_TO_ARGS}"
        LOAD_ARGS="${BAKE_LOAD_ARGS}"
        docker buildx bake dev \
          --file compose.yaml \
          --set dev.cache-from=type=gha,scope=ci \
          ${CACHE_ARGS} \
          ${LOAD_ARGS}

  lint:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
    - *checkout_step

    - *setup_buildx_step

    - *bootstrap_step

    - *build_images_step

    - name: Build images with docker compose
      run: |
        docker compose build dev

    - name: Check formatting with ruff
      run: |
        docker compose run --rm --no-deps dev ruff format --check .

    - name: Lint with ruff
      run: |
        docker compose run --rm --no-deps dev ruff check .

    - name: Cleanup
      if: always()
      run: |
        docker compose down -v

  test:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
    - *checkout_step

    - *setup_buildx_step

    - *bootstrap_step

    - *build_images_step

    - name: Build images with docker compose
      run: |
        docker compose build

    - name: Run tests in dev container
      run: |
        docker compose run --rm dev pytest tests/ -v

    - name: Show Cassandra logs on failure
      if: failure()
      run: |
        docker compose logs cassandra

    - name: Cleanup
      if: always()
      run: |
        docker compose down -v

  typecheck:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
    - *checkout_step

    - *setup_buildx_step

    - *bootstrap_step

    - *build_images_step

    - name: Build images with docker compose
      run: |
        docker compose build dev

    - name: Run tests in dev container
      run: |
        docker compose run --no-deps --rm dev mypy

    - name: Show Cassandra logs on failure
      if: failure()
      run: |
        docker compose logs cassandra

    - name: Cleanup
      if: always()
      run: |
        docker compose down -v
